### ISSUE TITLE
Add support for std::sample

### ISSUE THREAD

**Issue by SuperWig** [effolkronium/random#12]
https://en.cppreference.com/w/cpp/algorithm/sample

**Comment by effolkronium** [comment]
As workaround you can use Random::get_engine()

But it returns its engine by value...

I think it would be nice to have access to an internal engine by reference to avoid such problem, and do not wrap every new API which requires random number generator

I'll add it soon

**Comment by effolkronium** [comment]
Now you're able use any external algorithm that requires random engine as parameter

`std::sample(itBeg, itEnd, std::back_inserter(out), 5, Random::engine( ));`
