### ISSUE TITLE
Custom Distributions

### ISSUE THREAD

**Issue by amirmasoudabdol** [effolkronium/random#15]
I'm trying to use `arma::gmm_full` to implemente a multivariate normal random number generator. Basically, I'm writing a wrapper around it and implementing my own `mvnorm_distribution`. To do so, I'm trying to comply with `std::*_distribution` concepts and managed to use `Random::get<mvnorm_distribution<>>(means, covs)` working as I wanted it. A call to this line will spit out an `arma::vec`. 

One thing that I don't know how to achieve with your library is the seeding. Since _armadillo_ uses a custom seeder, I don't know how to integrate that with your wrapper. I can set armadillo's seed via `arma_rng::set_random_seed(int)`. 

How would you approach this in your library? If it matters, I'm going to use the `random_local` when I manage to get everything working.

With a bit of more research, I can see [here](https://gitlab.com/conradsnicta/armadillo-code/blob/9.500.x/include/armadillo_bits/arma_rng_cxx11.hpp) that they support threading and also using `mt19937` as the engine. 

My [mvnorm_distribution](https://gist.github.com/amirmasoudabdol/052a543d6edd6edcc9ead87fffdc79a5) implementation.

**Comment by effolkronium** [comment]
Wait wait wait. The Random::get<mvnorm_distribution<>>(args) will forward all passed arguments to mvnorm_distribution constructor, and then it will call operator(m_engine) (the mt199937 by default in my lib)

It's a tricky way, my lib was created to satisfy the std engines and distribution interfaces

If you want use my lib in right way, i recommned to get out your  arma::gmm_full from mvnorm_distribution members, and rewrite the gmm_full in the way to support all methods like in mt19937

https://en.cppreference.com/w/cpp/numeric/random/mersenne_twister_engine

The right distribution interface workflow is to construct it, pass to constructor or sen via method its parameters, and invoke ::operator( ) and pass the engine to it;

And again, random_engine and custom_distribution classes is a different and not depended on each other

The set_random_seed should be renamed to seed (like in mt19937), then you will be able to use ArmaRandom_t::seed(42) method for seeding.

So without my lib your code should be able behave like this:

```
  std::random_device random_device; // create object for seeding
  arma::gmm_full engine{random_device()}; // create engine and seed it
  arma::mvnorm_distribution<> dist(1,9); // create distribution for integers with [1; 9] range
  auto random_number = dist(engine); // finally get a pseudo-randomrandom integer number
```

Then you can write like this:

`using ArmaRandom_t = effolkronium::random_local<arma::gmm_full>;`










If you are too laze and a little bad, you can just pass distribution as parameter by reference

```
mvnorm_distribution <> gamma{ 1.f, 2.f };
auto result = Random DOT get( gamma ); // return result of gamma.operator()( engine_ )
```
