### ISSUE TITLE
seeder is created on every instance dereference

### ISSUE THREAD

**Issue by BenjaminBeichler** [effolkronium/random#16]
Hi,

I'm currently using your lib and overwrite the seeding function and ask myself, whether this is intended. E.g. the static engine has the following code:

```
        static Engine& engine_instance( ) {
            Seeder seeder{ };
            static Engine engine{ seeder( ) };
            return engine;
        }
    };
```
this means, even if the engine is not created every time, the seeder is. I was simply confused that my seeding function was called more than once, when I debugged it. Is that intended? It might be expensive to always get data from random device, as in the default seeder
```
    /// Default seeder for 'random' classes
    struct seeder_default {
        /// return seed sequence
        std::seed_seq& operator() ( ) {
            // MinGW issue, std::random_device returns constant value
            // Use std::seed_seq with additional seed from C++ chrono
            return seed_seq;
        }
    private:
        std::seed_seq seed_seq{ {
                static_cast<std::uintmax_t>( std::random_device{ }( ) ),
                static_cast<std::uintmax_t>( std::chrono::steady_clock::now( )
                                             .time_since_epoch( ).count( ) ),
        } };
    };
```
Maybe the compiler is sometimes clever enough to omit the creation (as the variable is only used, when the static is initialized), but it would be the same result if the Seeder is also simply static, isn't it?

**Comment by effolkronium** [comment]
Probably you're right. It is better to make seeder static as well. i'll try to implement this later ;)

**Comment by effolkronium** [comment]
hmmmmmmmmmmmmmmmmmmmmmmm

guess i've remembered why seeder is not static

Every engine instance will not store second Seeder field together with Engine.
Why?
To avoid store extra memory inside random instances
Why?
Because the main use-case of Seeder is to be created ONCE, retrieved seed value and pass it to the randomengine ONCE. 
That's it, the seeder goal will be achieved, and store its state for the all process lifetime is useless

@ricky65  Didn't u think so ?

**Comment by effolkronium** [comment]
but, the Seeder seeder{ }; is indeed creating every time in engine_instance 👍 
i'll remove it :D

**Comment by effolkronium** [comment]
@BenjaminBeichler done
https://github.com/effolkronium/random/releases/tag/v1.3.1

**Comment by BenjaminBeichler** [comment]
nice ! sorry for late answer
