### ISSUE TITLE
Suggestion: custom distribution for iterator

### ISSUE THREAD

**Issue by krofik** [effolkronium/random#17]
Right now, random iterator uses uniform distribution over container. I can imagine myself, that in some cases it might be useful to have possibility to apply custom distributions. For example, triangular distribution with the peak in the middle of array. I imagine that being used like already `Random::get<std::*_distribution<>>(array.begin(), array.end())`.

**Comment by effolkronium** [comment]
I'll take a look

**Comment by effolkronium** [comment]
The distribution for iterator\container shell support MIN\MAX values as parameters in distribution constructor like the
uniform_int_distribution

BUT the uniform_int_distribution is the only dist that support the requirements in C++ standard


I think its too complicated to hold up the requirement for other distributions, so for such custom logic U should write your own algorithm using the overloading with a custom distribution

For example:

```
std::array<int, 5> arr {1, 2, 3, 4, 5};
std::discrete_distribution<> d({40, 10, 10, 40});
auto resultRandomOffset = Random DOT get( d ); // return result of gamma.operator()( engine_ )
auto myRandIt = arr.begin() + resultRandomOffset;
```

If u have any questions or suggestions please write in the comments below
