### ISSUE TITLE
[Feature request] generates a vector of random numbers

### ISSUE THREAD

**Issue by Nelson-numerical-software** [effolkronium/random#24]
Currently, it is possible to generate a vector with a loop but it could be great to have a method to "quickly" generates an vector.

It could be:
```
Random::getVector<double>(-1, 1, N)
```

Thanks for your library

**Comment by effolkronium** [comment]
Hello

Support for random containers has been added in a recent 1.4.0 release

Resulting container elements type is automatically deducted from type of a two first arguments

Usage examples:

```
auto vec = Random::get<std::vector>(1, 9, 5); // decltype(vec) is std::vector<int> with size = 5
// Note: "reserve" method invokes automatically for performance

auto mset = Random::get<std::multiset>(1.0, 9.9, 10); // decltype(mset) is std::multiset<double> with size = 10

auto arr = Random::get<std::array, 5>('0', '9'); // decltype(arr) is std::array<char, 5>
// Warning: Returning arrays with large size could be ineficcient
```

**Comment by ilqvya** [comment]
Hi @wkingnet,

Try this:
`auto str = Random::get<std::string>('a', 'Z', 5);`

**Comment by wkingnet** [comment]
> Hi [@wkingnet](https://github.com/wkingnet),
> 
> Try this: `auto str = Random::get<std::string>('a', 'Z', 5);`

sorry, this code is invalid.

<img width="1041" height="258" alt="Image" src="https://github.com/user-attachments/assets/48b78b85-c92d-4bbf-a3c5-29805eb7d57b" />
