### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by tilongzs** [effolkronium/random#32]
> VisualStudio 2019
> C++ 20
![vs](https://user-images.githubusercontent.com/18590422/159198544-792559de-705c-4e86-a453-d277269271dc.jpg)
![random1](https://user-images.githubusercontent.com/18590422/159198709-6fadfda5-57b0-4390-8818-96fe1a4c2919.jpg)
I just included it and haven't done anything yet.

**Comment by effolkronium** [comment]
Look's like an issue with Windows.h header and C++ STL headers

Please, try NOMINMAX define
https://stackoverflow.com/questions/13416418/define-nominmax-using-stdmin-max

**Comment by effolkronium** [comment]
Fixed in commit:
https://github.com/effolkronium/random/pull/35/commits/0a55c7fe4429b9ce2bd9b6410d3d4abbd3885709

**Comment by tilongzs** [comment]
That 's great.
