### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by TurgutHarunArslan** [effolkronium/random#39]
#include <effolrandom.hpp>
im icluding like this, i have changed to this so it doesnt get with random.hpp, but even if it used how you give us it gives me this eror
error: 'Random' has not been declared
![image](https://user-images.githubusercontent.com/83730616/202924203-918f910b-0f94-422a-ad10-4c601833aa39.png)

**Comment by effolkronium** [comment]
Tell me your compiler name and version please. Ideally with some test project which reproduce this issue

**Comment by TurgutHarunArslan** [comment]
> Tell me your compiler name and version please. Ideally with some test project which reproduce this issue

i dont know what is it, i downloaded c++,then it said i needed a compiler so i watched a tutorial it write download mingw
is it mingw?

**Comment by effolkronium** [comment]
It could be mingw..... Maybe some old version or broken configs

What OS are you using ? For Windows the ideal way to write with cpp is downloading the Visual Studio 2022 with C++ package included and create C++ empty project inside its UI. It will be using latest Microsoft C++ compilers automatically

**Comment by TurgutHarunArslan** [comment]
im using windows with vscode, pretty sure u know better than me so im download vs2022,Thanks ill come when i download vs2022 and see if i get any errors!

**Comment by TurgutHarunArslan** [comment]
Hello im back after long time 
![image](https://user-images.githubusercontent.com/83730616/203143765-274cb816-25dc-4c67-94ba-43592ac5301a.png)
still getting errors

**Comment by effolkronium** [comment]
> Hello im back after long time
> image
> still getting errors

Cool, now you need to make sure that the effolkronium folder within the random.hpp file is placed in the same directory with main.cpp (file which contains main() function)

**Comment by TurgutHarunArslan** [comment]
yes i got it, now the only error is this
![image](https://user-images.githubusercontent.com/83730616/203145000-6c8bf802-22b4-4ac1-a854-bb0ae2d1d6f2.png)
the other one is fixed

**Comment by effolkronium** [comment]
Can you archive the "Rps" project entire folder and send it to me ?

**Comment by TurgutHarunArslan** [comment]
its only this file nothing else, u want the file?

**Comment by TurgutHarunArslan** [comment]
i got live share thing on visual studio
https://prod.liveshare.vsengsaas.visualstudio.com/join?B5462568C0AB7349D70C1CFCE86F27D88EB6

**Comment by effolkronium** [comment]
The VS 2022 project contains many other files. Right click on top of the "Rps" project name, select Open in folder (or something like this) and you'll see the folder

**Comment by TurgutHarunArslan** [comment]
do i send it, or u gonna come to this live share?

**Comment by TurgutHarunArslan** [comment]
Okay, i think i found how to send

**Comment by TurgutHarunArslan** [comment]
its saying, no permission to write file when trying to zip it

**Comment by effolkronium** [comment]
Copy folder to desktop, and zip there )

**Comment by effolkronium** [comment]
<img width="513" alt="image" src="https://user-images.githubusercontent.com/15274763/203146732-b1c0f172-e65a-4cb1-8f04-1998f0b8b6e7.png">

**Comment by TurgutHarunArslan** [comment]
i cant even run this on visual studio now.. it says cant find file rps.exe build failed

**Comment by effolkronium** [comment]
Wait, just got it.

The "Random" alias should be created by you like this:

```
#include "random.hpp"
using Random = effolkronium::random_static;
```

**Comment by TurgutHarunArslan** [comment]
im just gonna download mscv_x64 instead of mingw and try like that

**Comment by effolkronium** [comment]
> The "Random" alias should be created by you like this:

Read docs carefully ; )

**Comment by TurgutHarunArslan** [comment]
Oh... i didnt even see that even thought i just copy pasted that :D let me try

**Comment by TurgutHarunArslan** [comment]
Thanks Alot For helping me and this amazing work bro!
(i couldn't not even figure out how to make random number on my on with c++ 11)
👋
