### ISSUE TITLE
support for wide characters

### ISSUE THREAD

**Issue by darealshinji** [effolkronium/random#5]
I cannot use `wchar_t` directly, I can only cast between `wchar_t` and i.e. `long long`:
``` C++
#include <iostream>
#include <codecvt>
#include <locale>

std::wstring ws;

/* all characters from ㋐ to ㋾ */
std::cout << "㋐㋑㋒㋓㋔㋕㋖㋗㋘㋙㋚㋛㋜㋝㋞㋟㋠㋡㋢㋣㋤㋥㋦㋧㋨㋩㋪㋫㋬㋭㋮㋯㋰㋱㋲㋳㋴㋵㋶㋷㋸㋹㋺㋻㋼㋽㋾" << std::endl;

for (int i=0; i < 20; i++) {
  ws.push_back(Random::get<long long>(L'㋐', L'㋾'));
}

std::cout << std::wstring_convert<std::codecvt_utf8<wchar_t>>().to_bytes(ws) << std::endl;
```

In order to call `Random::get<wchar_t>()` I need to add `wchar_t` to `struct is_uniform_int`.

**Comment by effolkronium** [comment]
Indeed. But what if Random computes random character that will be invalid in UTF16 of UTF8 ?

Like one of surrogate pairs in UTF16 ?. (Which is wchar_t on Windows system)

Maybe, its better to store array of characters, and invoke 
`Rnadom::get(myCaracters);`

What you think?

**Comment by effolkronium** [comment]
Did you understood, that some characters in UTF-16 could be represented only by TWO uint16_t ???

Like  0xD840 0xDD23

http://graphemica.com/%F0%A0%84%A3


I think, that best way to prevent this bug, is to use 

static_cast<wchar_t>(Random::get<uint16_t>()); // Symbol could be invalid

???????

**Comment by effolkronium** [comment]
But probably, it does not matter... Men who uses "unsafe" ranges of variable UTF standards is a crazy noobs 🗡
